language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t st5703/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true st5703/react-test npm test

after_success:
  - docker build -t st5703/multi-client ./client
  - docker build -t st5703/multi-nginx ./nginx
  - docker build -t st5703/multi-server ./server
  - docker build -t st5703/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push st5703/multi-client
  - docker push st5703/multi-nginx
  - docker push st5703/multi-server
  - docker push st5703/multi-worker